// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/kalshi/pkg/kalshi (interfaces: KalshiClientLogic)
//
// Generated by this command:
//
//	mockgen -destination ../mocks/client_mock.go -package=mocks . KalshiClientLogic
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	kalshi "github.com/ggarcia209/kalshi/pkg/kalshi"
	gomock "go.uber.org/mock/gomock"
)

// MockKalshiClientLogic is a mock of KalshiClientLogic interface.
type MockKalshiClientLogic struct {
	ctrl     *gomock.Controller
	recorder *MockKalshiClientLogicMockRecorder
	isgomock struct{}
}

// MockKalshiClientLogicMockRecorder is the mock recorder for MockKalshiClientLogic.
type MockKalshiClientLogicMockRecorder struct {
	mock *MockKalshiClientLogic
}

// NewMockKalshiClientLogic creates a new mock instance.
func NewMockKalshiClientLogic(ctrl *gomock.Controller) *MockKalshiClientLogic {
	mock := &MockKalshiClientLogic{ctrl: ctrl}
	mock.recorder = &MockKalshiClientLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKalshiClientLogic) EXPECT() *MockKalshiClientLogicMockRecorder {
	return m.recorder
}

// CancelOrder mocks base method.
func (m *MockKalshiClientLogic) CancelOrder(ctx context.Context, orderID string) (*kalshi.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CancelOrder", ctx, orderID)
	ret0, _ := ret[0].(*kalshi.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CancelOrder indicates an expected call of CancelOrder.
func (mr *MockKalshiClientLogicMockRecorder) CancelOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CancelOrder", reflect.TypeOf((*MockKalshiClientLogic)(nil).CancelOrder), ctx, orderID)
}

// CreateOrder mocks base method.
func (m *MockKalshiClientLogic) CreateOrder(ctx context.Context, req kalshi.CreateOrderRequest) (*kalshi.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOrder", ctx, req)
	ret0, _ := ret[0].(*kalshi.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateOrder indicates an expected call of CreateOrder.
func (mr *MockKalshiClientLogicMockRecorder) CreateOrder(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOrder", reflect.TypeOf((*MockKalshiClientLogic)(nil).CreateOrder), ctx, req)
}

// DecreaseOrder mocks base method.
func (m *MockKalshiClientLogic) DecreaseOrder(ctx context.Context, orderID string, req kalshi.DecreaseOrderRequest) (*kalshi.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DecreaseOrder", ctx, orderID, req)
	ret0, _ := ret[0].(*kalshi.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DecreaseOrder indicates an expected call of DecreaseOrder.
func (mr *MockKalshiClientLogicMockRecorder) DecreaseOrder(ctx, orderID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DecreaseOrder", reflect.TypeOf((*MockKalshiClientLogic)(nil).DecreaseOrder), ctx, orderID, req)
}

// Event mocks base method.
func (m *MockKalshiClientLogic) Event(ctx context.Context, event string) (*kalshi.EventResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Event", ctx, event)
	ret0, _ := ret[0].(*kalshi.EventResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Event indicates an expected call of Event.
func (mr *MockKalshiClientLogicMockRecorder) Event(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockKalshiClientLogic)(nil).Event), ctx, event)
}

// Events mocks base method.
func (m *MockKalshiClientLogic) Events(ctx context.Context, req kalshi.EventsRequest) (*kalshi.EventsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, req)
	ret0, _ := ret[0].(*kalshi.EventsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockKalshiClientLogicMockRecorder) Events(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockKalshiClientLogic)(nil).Events), ctx, req)
}

// ExchangeSchedule mocks base method.
func (m *MockKalshiClientLogic) ExchangeSchedule(ctx context.Context) (*kalshi.ExchangeScheduleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeSchedule", ctx)
	ret0, _ := ret[0].(*kalshi.ExchangeScheduleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeSchedule indicates an expected call of ExchangeSchedule.
func (mr *MockKalshiClientLogicMockRecorder) ExchangeSchedule(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeSchedule", reflect.TypeOf((*MockKalshiClientLogic)(nil).ExchangeSchedule), ctx)
}

// ExchangeStatus mocks base method.
func (m *MockKalshiClientLogic) ExchangeStatus(ctx context.Context) (*kalshi.ExchangeStatusResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ExchangeStatus", ctx)
	ret0, _ := ret[0].(*kalshi.ExchangeStatusResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ExchangeStatus indicates an expected call of ExchangeStatus.
func (mr *MockKalshiClientLogicMockRecorder) ExchangeStatus(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ExchangeStatus", reflect.TypeOf((*MockKalshiClientLogic)(nil).ExchangeStatus), ctx)
}

// GetBalance mocks base method.
func (m *MockKalshiClientLogic) GetBalance(ctx context.Context) (kalshi.Cents, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBalance", ctx)
	ret0, _ := ret[0].(kalshi.Cents)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBalance indicates an expected call of GetBalance.
func (mr *MockKalshiClientLogicMockRecorder) GetBalance(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBalance", reflect.TypeOf((*MockKalshiClientLogic)(nil).GetBalance), ctx)
}

// GetFills mocks base method.
func (m *MockKalshiClientLogic) GetFills(ctx context.Context, req kalshi.FillsRequest) (*kalshi.FillsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFills", ctx, req)
	ret0, _ := ret[0].(*kalshi.FillsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFills indicates an expected call of GetFills.
func (mr *MockKalshiClientLogicMockRecorder) GetFills(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFills", reflect.TypeOf((*MockKalshiClientLogic)(nil).GetFills), ctx, req)
}

// GetOrder mocks base method.
func (m *MockKalshiClientLogic) GetOrder(ctx context.Context, orderID string) (*kalshi.Order, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrder", ctx, orderID)
	ret0, _ := ret[0].(*kalshi.Order)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrder indicates an expected call of GetOrder.
func (mr *MockKalshiClientLogicMockRecorder) GetOrder(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrder", reflect.TypeOf((*MockKalshiClientLogic)(nil).GetOrder), ctx, orderID)
}

// GetOrders mocks base method.
func (m *MockKalshiClientLogic) GetOrders(ctx context.Context, req kalshi.OrdersRequest) (*kalshi.OrdersResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOrders", ctx, req)
	ret0, _ := ret[0].(*kalshi.OrdersResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOrders indicates an expected call of GetOrders.
func (mr *MockKalshiClientLogicMockRecorder) GetOrders(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOrders", reflect.TypeOf((*MockKalshiClientLogic)(nil).GetOrders), ctx, req)
}

// GetPositions mocks base method.
func (m *MockKalshiClientLogic) GetPositions(ctx context.Context, req kalshi.PositionsRequest) (*kalshi.PositionsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPositions", ctx, req)
	ret0, _ := ret[0].(*kalshi.PositionsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPositions indicates an expected call of GetPositions.
func (mr *MockKalshiClientLogicMockRecorder) GetPositions(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPositions", reflect.TypeOf((*MockKalshiClientLogic)(nil).GetPositions), ctx, req)
}

// GetSettlements mocks base method.
func (m *MockKalshiClientLogic) GetSettlements(ctx context.Context, req kalshi.SettlementsRequest) (*kalshi.SettlementsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSettlements", ctx, req)
	ret0, _ := ret[0].(*kalshi.SettlementsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSettlements indicates an expected call of GetSettlements.
func (mr *MockKalshiClientLogicMockRecorder) GetSettlements(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSettlements", reflect.TypeOf((*MockKalshiClientLogic)(nil).GetSettlements), ctx, req)
}

// Market mocks base method.
func (m *MockKalshiClientLogic) Market(ctx context.Context, ticker string) (*kalshi.Market, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Market", ctx, ticker)
	ret0, _ := ret[0].(*kalshi.Market)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Market indicates an expected call of Market.
func (mr *MockKalshiClientLogicMockRecorder) Market(ctx, ticker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Market", reflect.TypeOf((*MockKalshiClientLogic)(nil).Market), ctx, ticker)
}

// MarketHistory mocks base method.
func (m *MockKalshiClientLogic) MarketHistory(ctx context.Context, ticker string, req kalshi.MarketHistoryRequest) (*kalshi.MarketHistoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarketHistory", ctx, ticker, req)
	ret0, _ := ret[0].(*kalshi.MarketHistoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarketHistory indicates an expected call of MarketHistory.
func (mr *MockKalshiClientLogicMockRecorder) MarketHistory(ctx, ticker, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarketHistory", reflect.TypeOf((*MockKalshiClientLogic)(nil).MarketHistory), ctx, ticker, req)
}

// MarketOrderBook mocks base method.
func (m *MockKalshiClientLogic) MarketOrderBook(ctx context.Context, ticker string) (*kalshi.OrderBook, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarketOrderBook", ctx, ticker)
	ret0, _ := ret[0].(*kalshi.OrderBook)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MarketOrderBook indicates an expected call of MarketOrderBook.
func (mr *MockKalshiClientLogicMockRecorder) MarketOrderBook(ctx, ticker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarketOrderBook", reflect.TypeOf((*MockKalshiClientLogic)(nil).MarketOrderBook), ctx, ticker)
}

// Markets mocks base method.
func (m *MockKalshiClientLogic) Markets(ctx context.Context, req kalshi.MarketsRequest) (*kalshi.MarketsResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Markets", ctx, req)
	ret0, _ := ret[0].(*kalshi.MarketsResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Markets indicates an expected call of Markets.
func (mr *MockKalshiClientLogicMockRecorder) Markets(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Markets", reflect.TypeOf((*MockKalshiClientLogic)(nil).Markets), ctx, req)
}

// Series mocks base method.
func (m *MockKalshiClientLogic) Series(ctx context.Context, seriesTicker string) (*kalshi.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Series", ctx, seriesTicker)
	ret0, _ := ret[0].(*kalshi.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Series indicates an expected call of Series.
func (mr *MockKalshiClientLogicMockRecorder) Series(ctx, seriesTicker any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Series", reflect.TypeOf((*MockKalshiClientLogic)(nil).Series), ctx, seriesTicker)
}

// Trades mocks base method.
func (m *MockKalshiClientLogic) Trades(ctx context.Context, req kalshi.TradesRequest) (*kalshi.TradesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trades", ctx, req)
	ret0, _ := ret[0].(*kalshi.TradesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Trades indicates an expected call of Trades.
func (mr *MockKalshiClientLogicMockRecorder) Trades(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trades", reflect.TypeOf((*MockKalshiClientLogic)(nil).Trades), ctx, req)
}
