// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ggarcia209/kalshi/pkg/kalshi (interfaces: KeySignerLogic)
//
// Generated by this command:
//
//	mockgen -destination ../mocks/signing.go -package=mocks . KeySignerLogic
//

// Package mocks is a generated GoMock package.
package mocks

import (
	http "net/http"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockKeySignerLogic is a mock of KeySignerLogic interface.
type MockKeySignerLogic struct {
	ctrl     *gomock.Controller
	recorder *MockKeySignerLogicMockRecorder
	isgomock struct{}
}

// MockKeySignerLogicMockRecorder is the mock recorder for MockKeySignerLogic.
type MockKeySignerLogicMockRecorder struct {
	mock *MockKeySignerLogic
}

// NewMockKeySignerLogic creates a new mock instance.
func NewMockKeySignerLogic(ctrl *gomock.Controller) *MockKeySignerLogic {
	mock := &MockKeySignerLogic{ctrl: ctrl}
	mock.recorder = &MockKeySignerLogicMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockKeySignerLogic) EXPECT() *MockKeySignerLogicMockRecorder {
	return m.recorder
}

// SignRequestWithRSAKey mocks base method.
func (m *MockKeySignerLogic) SignRequestWithRSAKey(req *http.Request) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SignRequestWithRSAKey", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SignRequestWithRSAKey indicates an expected call of SignRequestWithRSAKey.
func (mr *MockKeySignerLogicMockRecorder) SignRequestWithRSAKey(req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SignRequestWithRSAKey", reflect.TypeOf((*MockKeySignerLogic)(nil).SignRequestWithRSAKey), req)
}
